import { ComicStory } from '../types/comic';

export const SAMPLE_COMICS: ComicStory[] = [
  {
    id: 'sample-chrono-chaser',
    title: 'THE CHRONO-CHASER',
    subtitle: 'Issue #1: Paradox at Platform 9',
    genre: 'Sci-Fi',
    artStyle: 'Classic Retro Comic',
    tone: 'Action-Packed & Epic',
    issueNumber: 1,
    date: 'OCT 1984',
    synopsis: 'Time-agent Maya Cruz races against a temporal paradox before the 5:15 bullet train fractures reality itself.',
    characterProfiles: [
      {
        name: 'Maya Cruz',
        description: 'Elite chrononaut field agent with quick reflexes and dry wit.',
        costumeOrAppearance: 'Crimson leather flight jacket, brass chronometer gauntlet on left wrist, raven-black ponytail, goggles.',
      },
      {
        name: 'Dr. Vane',
        description: 'Rogue temporal physicist trying to rewrite his own regrets.',
        costumeOrAppearance: 'Charcoal high-collared trench coat, silver-streaked slicked hair, glowing cobalt pocket watch.',
      },
    ],
    panels: [
      {
        panelNumber: 1,
        caption: 'NEO-CHICAGO, 2089. SECONDS BEFORE THE TIMELINE FRACTURES...',
        sceneDescription: 'Maya Cruz crouches on the iron catwalk of a crowded retro-futuristic train station, rain glistening on her jacket as sparks shower from an overhead clock tower.',
        dialogues: [
          {
            id: 'd-1-1',
            character: 'Maya Cruz',
            text: "Gauntlet's humming. Vane's temporal rift opens in thirty seconds!",
            bubbleType: 'thought',
          },
        ],
        soundEffect: 'TICK-TOCK',
        soundEffectPosition: 'top-right',
        imagePrompt: 'Neo-futuristic rain-slicked train platform at dusk, steam and blue sparks, female hero Maya Cruz in crimson flight jacket and brass gauntlet, dynamic Dutch angle, Ben-Day halftone retro comic ink style',
        visualMood: 'Moody neon rain with electric blue sparks',
        cameraAngle: 'High angle looking down on bustling platform',
      },
      {
        panelNumber: 2,
        caption: 'PLATFORM 9. THE AIR BEGINS TO WARP AND TEAR!',
        sceneDescription: 'Dr. Vane stands amidst distorted violet spacetime ripples, his glowing cobalt pocket watch unspooling ribbons of luminescent temporal threads.',
        dialogues: [
          {
            id: 'd-2-1',
            character: 'Dr. Vane',
            text: 'You cannot arrest a man who has already erased tomorrow, Agent Cruz!',
            bubbleType: 'shout',
          },
        ],
        soundEffect: 'VROOOM!',
        soundEffectPosition: 'center',
        imagePrompt: 'Distorted reality swirling in violet spirals, rogue scientist Dr. Vane in charcoal coat holding radiant blue pocket watch, shattered glass temporal effect, comic graphic novel style',
        visualMood: 'Surreal violet vortex and chromatic aberration',
        cameraAngle: 'Dramatic low-angle worm-eye heroic villain perspective',
      },
      {
        panelNumber: 3,
        caption: 'A LEAP ACROSS SPLINTERED SECONDS!',
        sceneDescription: 'Maya dives headfirst off the catwalk, brass gauntlet firing a golden tachyon tether straight at the temporal core.',
        dialogues: [
          {
            id: 'd-3-1',
            character: 'Maya Cruz',
            text: 'Not on my watch, Doc!',
            bubbleType: 'shout',
          },
        ],
        soundEffect: 'KRAK-THOOM!',
        soundEffectPosition: 'top-left',
        imagePrompt: 'Hero mid-air dive with brass chronometer gauntlet blasting golden lightning tether, speed lines radiating outward, explosive comic action panel',
        visualMood: 'High-octane golden energy burst',
        cameraAngle: 'Extreme dynamic action shot with radial motion lines',
      },
      {
        panelNumber: 4,
        caption: 'THE CLOCK STRIKES ZERO. REALITY SNAPS BACK.',
        sceneDescription: 'The rift collapses into a shower of harmless golden embers. Maya stands over the deactivated chronometer, tipping her goggles with a smirk.',
        dialogues: [
          {
            id: 'd-4-1',
            character: 'Maya Cruz',
            text: 'Just another Monday in the fourth dimension.',
            bubbleType: 'speech',
          },
          {
            id: 'd-4-2',
            character: 'Maya Cruz',
            text: 'Now where did I park the time-skiff?',
            bubbleType: 'thought',
          },
        ],
        soundEffect: 'CLICK',
        soundEffectPosition: 'bottom-left',
        imagePrompt: 'Cool, confident female time-agent Maya Cruz tipping goggles with glowing embers floating down, steam drifting, morning sun rising behind station arches, vintage comic pop art',
        visualMood: 'Warm golden sunrise with triumphant relief',
        cameraAngle: 'Medium close-up hero shot with warm backlighting',
      },
    ],
  },
  {
    id: 'sample-goblin-cake',
    title: 'THE GOBLIN BAKER’S GAMBIT',
    subtitle: 'Issue #4: Flour, Fire & Fury',
    genre: 'Fantasy',
    artStyle: 'Saturday Morning Cartoon',
    tone: 'Witty & Humorous',
    issueNumber: 4,
    date: 'NOV 1992',
    synopsis: 'Grizzle the goblin baker must bake a three-tier enchanted chocolate volcano cake before the Dragon King gets hangry.',
    characterProfiles: [
      {
        name: 'Grizzle',
        description: 'An anxious goblin pastry chef with oversized chef hat and wooden rolling pin.',
        costumeOrAppearance: 'Green skin, long floppy ears, giant white chef hat tilted sideways, flour-dusted polka dot apron.',
      },
      {
        name: 'Ignis',
        description: 'A grumpy ruby dragon who doubles as an oven.',
        costumeOrAppearance: 'Scarlet dragon with gold horns, tiny reading glasses, and an oven mitt on one claw.',
      },
    ],
    panels: [
      {
        panelNumber: 1,
        caption: 'INSIDE CASTLE PYRE’S ROYAL KITCHEN...',
        sceneDescription: 'Grizzle desperately tosses enchanted exploding yeast into a colossal brass mixing bowl that is bubbling ominously.',
        dialogues: [
          {
            id: 'd-g-1',
            character: 'Grizzle',
            text: 'Two pinches of dragon pepper... or was it two pounds?!',
            bubbleType: 'shout',
          },
        ],
        soundEffect: 'GLUG-GLUG!',
        soundEffectPosition: 'top-right',
        imagePrompt: 'Whimsical fantasy castle kitchen, frantic goblin pastry chef in giant chef hat dumping glowing spice into massive bubbling copper pot, cartoony Saturday morning comic style',
        visualMood: 'Chaotic warm orange and flour clouds',
        cameraAngle: 'Wide dynamic kitchen scene',
      },
      {
        panelNumber: 2,
        caption: 'THE DRAGON SNORES, AND OVEN PREHEATS TO MAXIMUM!',
        sceneDescription: 'Ignis the dragon sneezes a tiny puff of emerald flame right into the cake pan, causing the chocolate batter to rise exponentially.',
        dialogues: [
          {
            id: 'd-g-2',
            character: 'Ignis',
            text: 'Achoo! <snort> Needs more cinnamon.',
            bubbleType: 'speech',
          },
        ],
        soundEffect: 'FOOOSH!',
        soundEffectPosition: 'center',
        imagePrompt: 'Red cartoon dragon with reading glasses sneezing green magical flame onto a giant towering chocolate cake in medieval oven, funny expressive cartoon art style',
        visualMood: 'Fiery emerald and crimson glow',
        cameraAngle: 'Close-up on dragon sneeze and expanding cake',
      },
      {
        panelNumber: 3,
        caption: 'THE BATTER STRIKES BACK!',
        sceneDescription: 'The giant chocolate cake explodes out of the oven into a gigantic chocolate tsunami heading straight for Grizzle.',
        dialogues: [
          {
            id: 'd-g-3',
            character: 'Grizzle',
            text: 'TASTE TEST INCOMING!',
            bubbleType: 'shout',
          },
        ],
        soundEffect: 'KABLAMMO!',
        soundEffectPosition: 'top-left',
        imagePrompt: 'Giant chocolate frosting tidal wave splashing through stone castle archway, funny goblin holding up tiny wooden spoon as a shield, dynamic animated comic strip style',
        visualMood: 'High contrast comic slapstick',
        cameraAngle: 'Action perspective looking up at oncoming chocolate wave',
      },
      {
        panelNumber: 4,
        caption: 'FIVE MINUTES LATER...',
        sceneDescription: 'Grizzle and Ignis sit covered head-to-toe in delicious fudge, each holding a spoon, utterly satisfied.',
        dialogues: [
          {
            id: 'd-g-4',
            character: 'Ignis',
            text: 'Best disaster you’ve ever baked, Grizzle.',
            bubbleType: 'speech',
          },
          {
            id: 'd-g-5',
            character: 'Grizzle',
            text: 'Next time, we try souffle.',
            bubbleType: 'whisper',
          },
        ],
        soundEffect: 'SLURP',
        soundEffectPosition: 'bottom-left',
        imagePrompt: 'Goblin chef and dragon sitting on kitchen floor drenched in fudge, smiling goofy smiles with spoons in hand, cozy warm cartoon comic illustration',
        visualMood: 'Sweet, cozy aftermath with gooey chocolate textures',
        cameraAngle: 'Cute two-shot eye-level friendly scene',
      },
    ],
  },
];
